"""rename sequence to cell_number

Revision ID: 206c32e0128b
Revises: 5f4f7615e37e
Create Date: 2023-09-06 15:33:29.486605

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "206c32e0128b"
down_revision = "5f4f7615e37e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cells",
        sa.Column(
            "cell_number",
            sa.Integer(),
            nullable=False,
            comment="number of cell in experiment",
        ),
    )
    op.drop_index("idx_experiment_uid_seq", table_name="cells")
    op.create_unique_constraint(
        "idx_experiment_uid_cell_number", "cells", ["experiment_uid", "cell_number"]
    )
    op.drop_column("cells", "sequence")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cells",
        sa.Column(
            "sequence",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
            comment="sequence number of cell in experiment",
        ),
    )
    op.drop_constraint("idx_experiment_uid_cell_number", "cells", type_="unique")
    op.create_index(
        "idx_experiment_uid_seq", "cells", ["experiment_uid", "sequence"], unique=False
    )
    op.drop_column("cells", "cell_number")
    # ### end Alembic commands ###
