"""add group organization_id

Revision ID: 51fca12beea5
Revises: bdcb1b1cc4b9
Create Date: 2023-10-25 09:26:00.578035

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "51fca12beea5"
down_revision = "bdcb1b1cc4b9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "groups",
        sa.Column("organization_id", mysql.BIGINT(unsigned=True), nullable=False),
    )
    op.create_index(
        op.f("ix_groups_organization_id"), "groups", ["organization_id"], unique=False
    )
    op.create_foreign_key(None, "groups", "organization", ["organization_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "groups", type_="foreignkey")
    op.drop_index(op.f("ix_groups_organization_id"), table_name="groups")
    op.drop_column("groups", "organization_id")
    # ### end Alembic commands ###
