"""add sequence to cells

Revision ID: 5f4f7615e37e
Revises: 8bc9b02be8ca
Create Date: 2023-09-05 01:14:01.713867

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5f4f7615e37e"
down_revision = "8bc9b02be8ca"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cells",
        sa.Column(
            "sequence",
            sa.Integer(),
            nullable=False,
            comment="sequence number of cell in experiment",
        ),
    )
    op.create_unique_constraint(
        "idx_experiment_uid_seq", "cells", ["experiment_uid", "sequence"]
    )
    op.drop_index(
        "ix_experiments_share_users_experiment_uid",
        table_name="experiments_share_users",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_experiments_share_users_experiment_uid",
        "experiments_share_users",
        ["experiment_uid"],
        unique=False,
    )
    op.drop_constraint("idx_experiment_uid_seq", "cells", type_="unique")
    op.drop_column("cells", "sequence")
    # ### end Alembic commands ###
