"""add index and fk for cell and exp

Revision ID: 7c823187d3c1
Revises: b66427b57c69
Create Date: 2023-09-15 08:09:47.529075

"""
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "7c823187d3c1"
down_revision = "b66427b57c69"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cells",
        "experiment_uid",
        existing_type=mysql.BIGINT(display_width=20, unsigned=True),
        comment=None,
        existing_comment="foregn key for experiments.id",
        existing_nullable=False,
    )
    op.create_index(
        "cells_id_created_at_updated_at_index",
        "cells",
        ["id", "created_at", "updated_at"],
        unique=False,
    )
    op.create_foreign_key(
        "cells_ibfk_1", "cells", "experiments", ["experiment_uid"], ["id"]
    )
    op.create_index(
        "experiments_id_experiment_id_publish_status_index",
        "experiments",
        ["id", "experiment_id", "publish_status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "experiments_id_experiment_id_publish_status_index", table_name="experiments"
    )
    op.drop_constraint("cells_ibfk_1", "cells", type_="foreignkey")
    op.drop_index("cells_id_created_at_updated_at_index", table_name="cells")
    op.alter_column(
        "cells",
        "experiment_uid",
        existing_type=mysql.BIGINT(display_width=20, unsigned=True),
        comment="foregn key for experiments.id",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
