"""add cell index

Revision ID: 84296a33ffd2
Revises: 7c823187d3c1
Create Date: 2023-10-16 19:48:46.369724

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "84296a33ffd2"
down_revision = "7c823187d3c1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "experiments_id_org_id_experiment_id_publish_status_index",
        "experiments",
        ["organization_id", "id", "experiment_id", "publish_status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "experiments_id_org_id_experiment_id_publish_status_index",
        table_name="experiments",
    )
    # ### end Alembic commands ###
