"""add foreignkey

Revision ID: 8bc9b02be8ca
Revises: 965cb1594a40
Create Date: 2023-08-05 21:29:46.894018

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "8bc9b02be8ca"
down_revision = "965cb1594a40"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE experiments "
        "MODIFY COLUMN organization_id BIGINT UNSIGNED NOT NULL;"
    )
    op.execute(
        "ALTER TABLE experiments_share_users "
        "MODIFY COLUMN experiment_uid BIGINT UNSIGNED NOT NULL;"
    )
    op.execute(
        "ALTER TABLE experiments_share_users "
        "MODIFY COLUMN user_id BIGINT UNSIGNED NOT NULL;"
    )
    op.execute(
        "ALTER TABLE user_roles " "MODIFY COLUMN user_id BIGINT UNSIGNED NOT NULL;"
    )
    op.execute(
        "ALTER TABLE user_roles " "MODIFY COLUMN role_id BIGINT UNSIGNED NOT NULL;"
    )
    op.execute(
        "ALTER TABLE users " "MODIFY COLUMN organization_id BIGINT UNSIGNED NOT NULL;"
    )
    op.execute(
        "ALTER TABLE workspaces_share_users "
        "MODIFY COLUMN workspace_id BIGINT UNSIGNED NOT NULL;"
    )
    op.execute(
        "ALTER TABLE workspaces_share_users "
        "MODIFY COLUMN user_id BIGINT UNSIGNED NOT NULL;"
    )
    op.create_foreign_key(
        None, "experiments", "organization", ["organization_id"], ["id"]
    )
    op.create_foreign_key(
        None, "experiments_share_users", "experiments", ["experiment_uid"], ["id"]
    )
    op.create_foreign_key(None, "experiments_share_users", "users", ["user_id"], ["id"])
    op.create_foreign_key(None, "user_roles", "users", ["user_id"], ["id"])
    op.create_foreign_key(None, "user_roles", "roles", ["role_id"], ["id"])
    op.create_foreign_key(None, "users", "organization", ["organization_id"], ["id"])
    op.create_foreign_key(
        None, "workspaces_share_users", "workspaces", ["workspace_id"], ["id"]
    )
    op.create_foreign_key(None, "workspaces_share_users", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "workspaces_share_users", type_="foreignkey")
    op.drop_constraint(None, "workspaces_share_users", type_="foreignkey")
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_constraint(None, "user_roles", type_="foreignkey")
    op.drop_constraint(None, "user_roles", type_="foreignkey")
    op.drop_constraint(None, "experiments_share_users", type_="foreignkey")
    op.drop_constraint(None, "experiments_share_users", type_="foreignkey")
    op.drop_constraint(None, "experiments", type_="foreignkey")
    op.execute(
        "ALTER TABLE experiments " "MODIFY COLUMN organization_id INTEGER NOT NULL;"
    )
    op.execute(
        "ALTER TABLE experiments_share_users "
        "MODIFY COLUMN experiment_uid INTEGER NOT NULL;"
    )
    op.execute(
        "ALTER TABLE experiments_share_users " "MODIFY COLUMN user_id INTEGER NOT NULL;"
    )
    op.execute("ALTER TABLE user_roles " "MODIFY COLUMN user_id INTEGER NOT NULL;")
    op.execute("ALTER TABLE user_roles " "MODIFY COLUMN role_id INTEGER NOT NULL;")
    op.execute("ALTER TABLE users " "MODIFY COLUMN organization_id INTEGER NOT NULL;")
    op.execute(
        "ALTER TABLE workspaces_share_users "
        "MODIFY COLUMN workspace_id INTEGER NOT NULL;"
    )
    op.execute(
        "ALTER TABLE workspaces_share_users " "MODIFY COLUMN user_id INTEGER NOT NULL;"
    )
    # ### end Alembic commands ###
