"""create foreignkey for user_id

Revision ID: 965cb1594a40
Revises: 73d4d7abcd35
Create Date: 2023-08-01 18:27:33.077883

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "965cb1594a40"
down_revision = "73d4d7abcd35"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE workspaces " "MODIFY COLUMN user_id BIGINT UNSIGNED NOT NULL;"
    )
    op.drop_index("ix_workspaces_user_id", table_name="workspaces")
    op.create_foreign_key("user", "workspaces", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user", "workspaces", type_="foreignkey")
    op.create_index("ix_workspaces_user_id", "workspaces", ["user_id"], unique=False)
    op.execute("ALTER TABLE workspaces " "MODIFY COLUMN user_id INTEGER NOT NULL;")
    # ### end Alembic commands ###
