"""add group unique constraint

Revision ID: c933537b9064
Revises: 51fca12beea5
Create Date: 2023-10-25 10:58:24.675928

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "c933537b9064"
down_revision = "51fca12beea5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "idx_name_org_id", "groups", ["organization_id", "name"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("idx_name_org_id", "groups", type_="unique")
    # ### end Alembic commands ###
