"""v0.2

Revision ID: f964bb3a47a4
Revises: cfec6fb68b66
Create Date: 2023-07-13 18:19:11.531296

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "f964bb3a47a4"
down_revision = "cfec6fb68b66"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organization",
        sa.Column("id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("belongs")
    op.add_column(
        "cells",
        sa.Column(
            "experiment_seqid",
            sa.Integer(),
            nullable=False,
            comment="foregn key for experiments.id",
        ),
    )
    op.drop_index("ix_cells_exp_id", table_name="cells")
    op.create_index(
        op.f("ix_cells_experiment_seqid"), "cells", ["experiment_seqid"], unique=False
    )
    op.drop_column("cells", "exp_id")
    op.add_column(
        "experiments",
        sa.Column(
            "share_type",
            sa.Integer(),
            nullable=False,
            comment="1: default(per users), 2: for organization",
        ),
    )
    op.add_column(
        "experiments", sa.Column("organization_id", sa.Integer(), nullable=False)
    )
    op.alter_column(
        "experiments",
        "publish_status",
        existing_type=mysql.INTEGER(display_width=11),
        nullable=False,
        existing_comment="0: private, 1: public",
    )
    op.add_column("users", sa.Column("organization_id", sa.Integer(), nullable=False))
    op.drop_column("users", "belong_id")
    op.drop_index("idx_workspace_id", table_name="workspaces_share_users")
    op.create_unique_constraint(
        "idx_workspace_id_user_id",
        "workspaces_share_users",
        ["workspace_id", "user_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "idx_workspace_id_user_id", "workspaces_share_users", type_="unique"
    )
    op.create_index(
        "idx_workspace_id",
        "workspaces_share_users",
        ["workspace_id", "user_id"],
        unique=False,
    )
    op.add_column(
        "users",
        sa.Column(
            "belong_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("users", "organization_id")
    op.alter_column(
        "experiments",
        "publish_status",
        existing_type=mysql.INTEGER(display_width=11),
        nullable=True,
        existing_comment="0: private, 1: public",
    )
    op.drop_column("experiments", "organization_id")
    op.drop_column("experiments", "share_type")
    op.add_column(
        "cells",
        sa.Column(
            "exp_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
            comment="foregn key for experiments.id",
        ),
    )
    op.drop_index(op.f("ix_cells_experiment_seqid"), table_name="cells")
    op.create_index("ix_cells_exp_id", "cells", ["exp_id"], unique=False)
    op.drop_column("cells", "experiment_seqid")
    op.create_table(
        "belongs",
        sa.Column(
            "id",
            mysql.BIGINT(display_width=20, unsigned=True),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("belong", mysql.VARCHAR(length=100), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(),
            server_default=sa.text("current_timestamp()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="latin1_swedish_ci",
        mysql_default_charset="latin1",
        mysql_engine="InnoDB",
    )
    op.drop_table("organization")
    # ### end Alembic commands ###
