name: Tests

on:
  pull_request:
    branches:
      - main
      - develop-main
    paths-ignore:
      - 'docs/**'

  workflow_dispatch:

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin

      - name: Run test_run command
        shell: bash
        run: |
          make test_run
